version: '3.8'

services:
    chrome:
        image: selenium/standalone-chrome:latest
        hostname: chrome
        privileged: true
        shm_size: 2g
        ports:
          - "4444:4444"
    tests:
        build: .
        links:
          - chrome
        depends_on: 
            - chrome
